create or replace task TASK_REFRESH_ERROR_LOG
	warehouse=WH_LOAD
	schedule='USING CRON 05 9 * * * Asia/Tokyo'
	as CREATE OR REPLACE TABLE IOT.IOT_RAW.OPS_ERROR_LOG AS
  SELECT
    RUN_AT,
    SYSTEM,
    DATASET,
    TARGET_TABLE,
    FILE_PATH,
    FILE_NAME,
    STATUS,
    ERRORS_SEEN,
    FIRST_ERROR_MESSAGE,
    ERROR_FLAG,
    RAW
  FROM IOT.IOT_RAW.OPS_RUN_LOG
  WHERE ERROR_FLAG = TRUE;