create or replace task TASK_REFRESH_RECOVERY_QUEUE
	warehouse=WH_LOAD
	schedule='USING CRON 07 9 * * * Asia/Tokyo'
	as CREATE OR REPLACE TABLE IOT.IOT_RAW.OPS_RECOVERY_QUEUE AS
WITH CFG AS (
  SELECT SYSTEM, DATASET, SUBPATH
  FROM IOT.IOT_RAW.OPS_DATASET_CONFIG
),
NORM AS (
  SELECT
      E.RUN_AT,
      E.SYSTEM,
      E.DATASET,
      E.FILE_PATH,
      REGEXP_SUBSTR(E.FILE_PATH, '[^/]+$') AS FILE_NAME,
      CASE
        WHEN C.SUBPATH IS NOT NULL
         AND E.FILE_PATH IS NOT NULL
         AND POSITION(C.SUBPATH IN E.FILE_PATH) > 0
        THEN '/' || SUBSTR(
               E.FILE_PATH,
               POSITION(C.SUBPATH IN E.FILE_PATH) + LENGTH(C.SUBPATH)
             )
        ELSE E.FILE_PATH
      END AS PATTERN
  FROM IOT.IOT_RAW.OPS_ERROR_LOG E
  LEFT JOIN CFG C
    ON E.SYSTEM = C.SYSTEM
   AND E.DATASET = C.DATASET
  WHERE E.FILE_PATH IS NOT NULL
  QUALIFY ROW_NUMBER()
          OVER (PARTITION BY E.SYSTEM, E.DATASET, E.FILE_PATH
                ORDER BY E.RUN_AT DESC) = 1
)
SELECT
    N.SYSTEM,
    N.DATASET,
    N.PATTERN,
    TRUE                 AS FORCE,
    'PENDING'            AS STATUS,
    NULL::STRING         AS NOTE,
    CURRENT_TIMESTAMP()  AS CREATED_AT
FROM NORM N;