CREATE OR REPLACE FILE FORMAT IOT.IOT_RAW.FF_CSV_PROD_LOG_FH
  TYPE = CSV
  SKIP_HEADER = 1
  DATE_FORMAT = 'YYYY/MM/DD'
  TIME_FORMAT = 'HH24:MI:SS'
  TIMESTAMP_FORMAT = 'YYYY/MM/DD HH24:MI:SS'
  TRIM_SPACE = TRUE
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL')
  ENCODING = 'SHIFT_JIS'
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
;
