CREATE OR REPLACE FILE FORMAT FF_CSV_COMMON
	SKIP_HEADER = 1
	DATE_FORMAT = 'YYYY/MM/DD'
	TIME_FORMAT = 'HH24:MI:SS'
	TIMESTAMP_FORMAT = 'YYYY/MM/DD HH24:MI:SS'
	TRIM_SPACE = TRUE
	FIELD_OPTIONALLY_ENCLOSED_BY = '\"'
	NULL_IF = ('', 'NULL')
	ENCODING = 'SHIFT_JIS'
;