CREATE OR REPLACE PROCEDURE IOT.IOT_RAW.SP_LOAD_PROD_LOG_FH_RAW()
RETURNS VARCHAR
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS
' 
var sql = `
MERGE INTO IOT.IOT_RAW.PROD_LOG_FH_RAW T
USING (
  SELECT
    METADATA$FILENAME        AS SOURCE_FILE_PATH,
    METADATA$FILE_ROW_NUMBER AS SOURCE_ROW_NUMBER,
    OBJECT_CONSTRUCT_KEEP_NULL(*) AS RAW_OBJ,
    CURRENT_TIMESTAMP()      AS LOADED_AT
  FROM @IOT.IOT_RAW.MY_AZURE_STAGE/dataspider/IoT/Recv/
  (
    FILE_FORMAT => ''IOT.IOT_RAW.FF_CSV_PROD_LOG_FH'',
    PATTERN => ''.*Prod_log/.*\\\\.csv''
  )
) S
ON  T.SOURCE_FILE_PATH = S.SOURCE_FILE_PATH
AND T.SOURCE_ROW_NUMBER = S.SOURCE_ROW_NUMBER
WHEN NOT MATCHED THEN
  INSERT (SOURCE_FILE_PATH, SOURCE_ROW_NUMBER, RAW_OBJ, LOADED_AT)
  VALUES (S.SOURCE_FILE_PATH, S.SOURCE_ROW_NUMBER, S.RAW_OBJ, S.LOADED_AT)
`;

var stmt = snowflake.createStatement({ sqlText: sql });
stmt.execute();

return ''OK'';
';
