CREATE OR REPLACE PROCEDURE IOT.IOT_RAW.SP_REFRESH_PROD_LOG_FH()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
'
BEGIN
  CALL IOT.IOT_RAW.SP_LOAD_PROD_LOG_FH_RAW();
  CALL IOT.IOT_RAW.SP_NORMALIZE_PROD_LOG_FH();
  RETURN ''OK'';
END;
';
