CREATE OR REPLACE STAGE IOT.IOT_RAW.MY_AZURE_STAGE
  URL = 'azure://hrssnowflakedatafiles01.blob.core.windows.net/dataspider/'
  STORAGE_INTEGRATION = AZURE_INT
  FILE_FORMAT = (
    TYPE = CSV
    RECORD_DELIMITER = '\n'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 0
    PARSE_HEADER = FALSE
    DATE_FORMAT = 'AUTO'
    TIME_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
    BINARY_FORMAT = HEX
    ESCAPE = NONE
    ESCAPE_UNENCLOSED_FIELD = '\\'
    TRIM_SPACE = FALSE
    FIELD_OPTIONALLY_ENCLOSED_BY = NONE
    NULL_IF = ('\\N')
    COMPRESSION = AUTO
    ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE
    VALIDATE_UTF8 = TRUE
    SKIP_BLANK_LINES = FALSE
    REPLACE_INVALID_CHARACTERS = FALSE
    EMPTY_FIELD_AS_NULL = TRUE
    SKIP_BYTE_ORDER_MARK = TRUE
    ENCODING = UTF8
  )
  COPY_OPTIONS = (
    ON_ERROR = 'ABORT_STATEMENT'
    PURGE = FALSE
    RETURN_FAILED_ONLY = FALSE
    ENFORCE_LENGTH = TRUE
    TRUNCATECOLUMNS = FALSE
    FORCE = FALSE
  )
  DIRECTORY = (
    ENABLE = TRUE
    AUTO_REFRESH = FALSE
  );