CREATE OR REPLACE TABLE IOT.IOT_RAW.MC_LOG (
  "DATA No."                               STRING,
  "DATE"                                   DATE,
  "TIME"                                   TIME,
  "Nコード"                                 STRING,
  "ロットトレースNo."                       STRING,
  "製造指示書No."                           STRING,
  "ラインNo."                               STRING,
  "CAM3ﾜｰｸ有無"                             STRING,
  "信号端子平坦度1MAX[μm]"                 NUMBER(18,3),
  "電源端子平坦度1-1[μm]"                  NUMBER(18,3),
  "電源端子平坦度1-2[μm]"                  NUMBER(18,3),
  "金具平坦度1-1[μm]"                      NUMBER(18,3),
  "金具平坦度1-2[μm]"                      NUMBER(18,3),
  "信号端子平坦度2MAX[μm]"                 NUMBER(18,3),
  "電源端子平坦度2-1[μm]"                  NUMBER(18,3),
  "電源端子平坦度2-2[μm]"                  NUMBER(18,3),
  "金具平坦度2-1[μm]"                      NUMBER(18,3),
  "金具平坦度2-2[μm]"                      NUMBER(18,3),
  "金具ｷﾞｬｯﾌﾟ1[㎜]"                        NUMBER(18,3),
  "金具ｷﾞｬｯﾌﾟ2[㎜]"                        NUMBER(18,3),
  "信号端子ﾄｰﾀﾙﾋﾟｯﾁ1[㎜]"                  NUMBER(18,3),
  "信号電源端子ﾋﾟｯﾁ1-1[㎜]"                NUMBER(18,3),
  "信号電源端子ﾋﾟｯﾁ1-2[㎜]"                NUMBER(18,3),
  "信号端子ﾄｰﾀﾙﾋﾟｯﾁ2[㎜]"                  NUMBER(18,3),
  "信号電源端子ﾋﾟｯﾁ2-1[㎜]"                NUMBER(18,3),
  "信号電源端子ﾋﾟｯﾁ2-2[㎜]"                NUMBER(18,3),
  "金具ﾋﾟｯﾁ1[㎜]"                           NUMBER(18,3),
  "金具ﾋﾟｯﾁ2[㎜]"                           NUMBER(18,3),
  "爪傷L[単位無]"                           NUMBER(18,3),
  "爪傷R[単位無]"                           NUMBER(18,3)
);
